name: exa_gammer_movil
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/fondo/
    - assets/imagen/logo_exa.png
  fonts:
    - family: TitanOne
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
