###############################
# Configuración principal
###############################

sonar.projectKey=JJuvinao_exa_gammer_movil
sonar.organization=jjuvinao
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

###############################
# Rutas del proyecto Flutter
###############################

# Código fuente
sonar.sources=lib

# Archivos de prueba
sonar.tests=test

###############################
# Exclusiones para evitar ruido
###############################

sonar.exclusions=**/*.png, **/*.jpg, **/*.jpeg, **/*.gif, assets/**, build/**

###############################
# Configuración Dart / Flutter
###############################

# Indica a Sonar que use Flutter Analyzer
sonar.dart.analyzer.mode=flutter

# Ruta donde se generará el reporte
sonar.flutter.analyzer.reportPath=sonar-result.json
