sonar.projectKey=JJuvinao_exa_gammer_movil
sonar.organization=jjuvinao
sonar.host.url=https://sonarcloud.io

sonar.sources=lib
sonar.exclusions=**/*.png,**/*.jpg,**/*.gif,assets/**

# Desactivar el analizador Dart interno
sonar.dart.analysis.useBuiltin=false

# Usar el archivo generado por flutter analyze
sonar.flutter.analyzer.reportPath=sonar-result.json

sonar.sourceEncoding=UTF-8
