sonar.projectKey=JJuvinao_exa_gammer_movil
sonar.organization=jjuvinao

# Configuración de paths
sonar.sources=lib
sonar.tests=test

# Exclusiones
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,**/*.config.dart,**/*.pb.dart

# Encoding
sonar.sourceEncoding=UTF-8

# Cobertura de tests (si ejecutas tests)
sonar.dart.coverage.reportPaths=coverage/lcov.info

# Host (opcional, ya está por defecto)
sonar.host.url=https://sonarcloud.io