name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=JJuvinao_exa_gammer_movil
            -Dsonar.organization=jjuvinao
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=lib
            -Dsonar.exclusions=/.png,/.jpg,/.gif,/assets/*
            -Dsonar.sourceEncoding=UTF-8
