name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Flutter Analyze
        run: |
          flutter analyze --no-preamble --write=sonar-result.json || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=JJuvinao_exa_gammer_movil
            -Dsonar.organization=jjuvinao
            -Dsonar.sources=lib
            -Dsonar.exclusions=**/*.png,**/*.jpg,**/*.gif,assets/**
            -Dsonar.flutter.analyzer.reportPath=sonar-result.json
            -Dsonar.sourceEncoding=UTF-8
