name: SonarCloud
on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Run Flutter analyzer
        run: flutter analyze --write=sonar-result.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=JJuvinao_exa_gammer_movil
            -Dsonar.organization=jjuvinao
            -Dsonar.sources=lib
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.flutter.analyzer.reportPath=sonar-result.json
            -Dsonar.sourceEncoding=UTF-8
